#!/usr/bin/env bash

nix run nix-darwin -- switch --flake .#shodan

# nixos-rebuild switch --flake .#${1}
# darwin-rebuild switch --flake .#shodan

# nix run nix-darwin -- --flake github:tcurdt/nixcfg#shodan
# nix build .#darwinConfigurations.machine.config.system
# nix run nix-darwin -- switch --flake ~/.config/nix-darwin
# ./result/sw/bin/darwin-rebuild switch --flake .
# nix flake update
# darwin-rebuild switch --flake .
