apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdn-volume
  namespace: infra
  labels:
    app: cdn
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  # persistentVolumeReclaimPolicy: Retain
  hostPath:
    # mkdir -p /srv/volumes/cdn
    path: /srv/volumes/cdn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-volume-claim
  namespace: infra
  labels:
    app: cdn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    app: caddy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infra
  name: caddy
  labels:
    app: caddy
  # annotations:
  #   reloader.stakater.com/match: "true"
data:
  Caddyfile: |
    {
      email "tcurdt@vafer.org"
      admin :2019
      servers {
        metrics
      }
      acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
    }

    live.vafer.org {
      tls internal
      header -server

      # if file "maintenance" exists on disk show maintenance

      @exists {
        file /srv/volumes/cdn/maintenance
      }

      handle @exists {
        respond "We will be back shortly" 503 {
          close
        }
      }

      # otherwise pass on to proxy

      handle {
        reverse_proxy http://backend.live.svc.cluster.local:80
      }
    }

    test.vafer.org {
      tls internal
      header -server

      # respond "We will be back shortly" 503 {
      #   close
      # }

      reverse_proxy http://backend.test.svc.cluster.local:80
    }

    cdn.vafer.org {
      tls internal
      header -server

      # header {
      #   content-security-policy img-src 'self' app.edkimo.com
      #   content-security-policy-report-only policy
      #   access-control-allow-origin https://app.edkimo.com
      #   access-control-allow-methods GET, OPTIONS, HEAD
      #   cache-control public, max-age=86400
      #   x-content-type-options nosniff
      #   x-frame-options deny
      # }

      root * /srv/volumes/cdn
      file_server
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: caddy
  labels:
    app: caddy
  # annotations:
  #   reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:2.7.6-alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
        - name: cdn-storage
          mountPath: /srv/volumes/cdn
        resources:
          limits:
            # cpu: 250m
            memory: 100Mi
          requests:
            # cpu: 100m
            memory: 200Mi
      volumes:
      - name: caddy-config
        configMap:
          name: caddy
      - name: cdn-storage
        persistentVolumeClaim:
          claimName: cdn-volume-claim
