# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   namespace: infra
#   name: promtail
# rules:
#   - apiGroups:
#       - ""
#     resources:
#       - nodes
#       - services
#       - pods
#     verbs:
#       - create
#       - update
#       - patch
#       - delete
#       - get
#       - watch
#       - list
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # name: deploy
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: infra
    name: deploy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: infra
  name: deploy
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: infra
  name: deploy
  labels:
    app: deploy
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deploy
          restartPolicy: OnFailure
          containers:
            - name: deploy
              image: bitnami/kubectl:1.27.14
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "deployment start"
                  kubectl get all -A
                  echo "deployment stop"
