apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  # persistentVolumeReclaimPolicy: Retain
  hostPath:
    # mkdir -p /srv/volumes/mysql
    path: /srv/volumes/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  namespace: infra
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: infra
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: infra
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # securityContext:
      #   runAsUser: 65534
      containers:
        - name: mysql
          image: mysql:8.4.0
          # image: mariadb:11.4.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-superuser
                  key: password
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            requests:
              # cpu: 100m
              memory: 200Mi
            limits:
              # cpu: 200m
              memory: 400Mi
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-volume-claim
