apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: prom-postgres-exporter
  labels:
    app: prom-postgres-exporter
spec:
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
  selector:
    app: prom-postgres-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: prom-postgres-exporter
  labels:
    app: prom-postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-postgres-exporter
  template:
    metadata:
      labels:
        app: prom-postgres-exporter
    spec:
      containers:
        - name: prom-postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.10.1
          args:
            - --log.level=error
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-superuser
                  key: url
          ports:
            - name: metrics
              containerPort: 9187
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 200Mi
