apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: prom-push-exporter
  labels:
    app: prom-push-exporter
  # annotations:
  #   prometheus.io/scrape: 'true'
  #   prometheus.io/port: '9091'
spec:
  selector:
    app: prom-push-exporter
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: prom-push-exporter
  labels:
    app: prom-push-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-push-exporter
  template:
    metadata:
      labels:
        app: prom-push-exporter
    spec:
      containers:
      - name: prom-push-exporter
        image: prom/pushgateway:v1.8.0
        ports:
        - name: http
          containerPort: 9091
        resources:
          requests:
            # cpu: 50m
            memory: 100Mi
          limits:
            # cpu: 100m
            memory: 200Mi
