apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: prom-postgres-exporter
  labels:
    app: prom-postgres-exporter
  # annotations:
  #   prometheus.io/scrape: 'true'
  #   prometheus.io/port: '9187'
spec:
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187
  selector:
    app: prom-postgres-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: prom-postgres-exporter
  labels:
    app: prom-postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-postgres-exporter
  template:
    metadata:
      labels:
        app: prom-postgres-exporter
    spec:
      containers:
      - name: prom-postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.10.1
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: url
        ports:
        - name: metrics
          containerPort: 9187
        resources:
          requests:
            # cpu: 100m
            memory: 100Mi
          limits:
            # cpu: 250m
            memory: 200Mi
