apiVersion: batch/v1
kind: Job
metadata:
  namespace: infra
  name: restore
  labels:
    app: restore
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: your-docker-image:tag
          env:
            - name: DB_HOST
              value: postgresql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-superuser
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-superuser
                  key: password

# curl
# age
# rclone
# aws cli