apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-volumes
  namespace: infra
  labels:
    app: deploy
    type: local
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /srv/volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-volumes-claim
  namespace: infra
  labels:
    app: deploy-apply
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: infra
  name: backup-volumes
  labels:
    app: backup-volumes
spec:
  schedule: "*/ * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-volumes
              image: alpine:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  whoami
                  ls -la /srv/volumes
              volumeMounts:
                - name: backup-volumes
                  mountPath: /srv/volumes
                  readOnly: true
              securityContext:
                # readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
          volumes:
            - name: backup-volumes
              persistentVolumeClaim:
                claimName: backup-volumes-claim
