apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: infra
  name: postgres-backup
  labels:
    app: postgres-backup
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: postgres-backup
              image: your-docker-image:tag
              env:
                - name: DB_HOST
                  value: postgresql
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-superuser
                      key: username
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-superuser
                      key: password

# curl
# age
# rclone
# aws cli