version: '3.6'

services:

  frontend:
    container_name: frontend
    image: docker.io/traefik/whoami:v1.9.0
    ports:
      - 8080:80
    # deploy:
    #   mode: replicated
    #   replicas: 2

  db:
    container_name: postgres
    image: docker.io/library/postgres:latest
    environment:
      - POSTGRES_DB=bluesky
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
