version: '3.6'

services:

  echo:
    container_name: echo
    image: ealen/echo-server
    ports:
      - 8080:80

  postgres:
    container_name: postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
