# kubectl create -f to import
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.infra.name: foo-infra
  creationTimestamp: "2023-10-25T21:05:21Z"
  labels:
    app: foo
  name: foo
spec:
  containers:
  - image: docker.io/ealen/echo-server:latest
    name: backend
    ports:
    - containerPort: 80
      hostPort: 8080

