apiVersion: v1
kind: Pod
metadata:
  name: echo-live
spec:
  containers:
  - name: frontend
    image: docker.io/traefik/whoami:v1.9.0
    ports:
      - containerPort: 80
  - name: db
    image: docker.io/library/postgres:latest
    env:
      - name: POSTGRES_DB
        value: echo-live
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: secret
    ports:
      - containerPort: 5432