apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: deploy-apply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-apply
  template:
    metadata:
      labels:
        app: deploy-apply
    spec:
      containers:
        - name: deploy-apply
          image: ghcr.io/tcurdt/kubeops:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              REPO=/tmp/repo
              while true; do

                rm -rf $REPO
                cp -r /git/current/kubernetes $REPO
                cd $REPO

                RESOLVED=$(oci-resolve)
                echo $RESOLVED
                sh <(echo $RESOLVED)

                # kubectl kustomize . | kubectl apply -f -
                # kustomize build /git/current | kubectl apply -f -

                sleep 60 # wait or webhook
              done
          volumeMounts:
            - name: infra-volume
              mountPath: /git
              readOnly: true
          securityContext:
            # readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: infra-volume
          persistentVolumeClaim:
            claimName: infra-volume-claim
