apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: deploy-apply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-apply
  template:
    metadata:
      labels:
        app: deploy-apply
    spec:
      containers:
        - name: deploy-apply
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "resolving oci images"
                echo "kubectl apply"
                echo "notify"
                ls -la /git/current
                sleep 30
              done
          volumeMounts:
            - name: infra-volume
              mountPath: /git
              readOnly: true
          securityContext:
            # readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: infra-volume
          persistentVolumeClaim:
            claimName: infra-volume-claim
