name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix flake check

  build-x86:
    name: build x86 systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [
            # "app",
            # "utm-arm",
            # "utm-x86",
            # "kube-edkimo",
            "kube-michael",
            # "home-goe",
            # "home-ber",
            # "rpi-zero,",
          ]
    steps:
      # - uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix build .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel

  # build-arm:
  #   name: build arm systems
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # architecture: [arm64]
  #       configuration: [
  #           "utm-arm",
  #           # "rpi-zero,",
  #         ]
  #   steps:
  #     - uses: actions/checkout@v7
  #     - uses: cachix/install-nix-action@v31
  #     - run: nix build .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel

  # build-darwin:
  #   name: build darwin systems
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v7
  #     - uses: cachix/install-nix-action@v31
  #     - run: nix build .#darwinConfigurations.WQ0C6FWJ1W.config.system.build.toplevel
